vim.cmd.highlight 'clear'
vim.g.colors_name = 'phoenix'
local hi = function(name, val)
  -- Force links
  val.force = true
  -- Make sure that `cterm` attribute is not populated from `gui`
  val.cterm = val.cterm or {} ---@type vim.api.keyset.highlight
  -- Define global highlight
  vim.api.nvim_set_hl(0, name, val)
end
vim.o.background = "light"
--stylua: ignore start
-- General UI
hi('Normal',                    { fg = '#000000',       bg = '#faf9f9' })
hi('Error',                     { fg = 'White',         bg = 'Red' })
hi('ErrorMsg',                  { fg = 'White',         bg = 'Red' })
hi('IncSearch',                 { reverse = true })
hi('NonText',                   { fg = 'Blue',          bg = '#efefef', bold = true })
hi('RedrawDebugClear',          { bg = 'Yellow' })
hi('RedrawDebugComposed',       { bg = 'Green3' })
hi('RedrawDebugRecompose',      { bg = 'Red' })
hi('StatusLine',                { bg = '#ffffff',       bold = true })
hi('StatusLineNC',              { reverse = true })
hi('TabLineFill',               { reverse = true })
hi('TabLineSel',                { bold = true })
hi('TermCursor',                { reverse = true })
hi('Todo',                      { fg = 'Blue',          bg = 'Yellow' })
hi('WildMenu',                  { fg = 'Black',         bg = 'Yellow' })
hi('WinBar',                    { bold = true })
hi('DiffText',                  { bg = 'Red',           bold = false })
hi('RedrawDebugNormal',         { reverse = true })
hi('CurSearch',                 { link = 'Search' })
hi('CursorLineFold',            { link = 'FoldColumn' })
hi('CursorLineSign',            { link = 'SignColumn' })
hi('EndOfBuffer',               { link = 'NonText' })
hi('FloatBorder',               { link = 'WinSeparator' })
hi('FloatFooter',               { link = 'Title' })
hi('FloatTitle',                { link = 'Title' })
hi('LineNrAbove',               { link = 'LineNr' })
hi('LineNrBelow',               { link = 'LineNr' })
hi('MsgSeparator',              { link = 'StatusLine' })
hi('NormalFloat',               { link = 'Pmenu' })
hi('QuickFixLine',              { link = 'Search' })
hi('Substitute',                { link = 'Search' })
hi('VertSplit',                 { link = 'Normal' })
hi('WinBarNC',                  { link = 'WinBar' })
hi('WinSeparator',              { link = 'VertSplit' })
hi('FloatShadow',               { bg = 'Black',         blend = 80 })
hi('FloatShadowThrough',        { bg = 'Black',         blend = 100 })
hi('Pmenu',                     { fg = 'Black',         bg = '#ffffff' })
hi('PmenuExtra',                { link = 'Pmenu' })
hi('PmenuExtraSel',             { link = 'PmenuSel' })
hi('PmenuKind',                 { link = 'Pmenu' })
hi('PmenuKindSel',              { link = 'PmenuSel' })
hi('PmenuMatch',                { link = 'Pmenu' })
hi('PmenuMatchSel',             { link = 'PmenuSel' })
hi('PmenuSbar',                 { bg = 'White' })
hi('PmenuSel',                  { fg = 'White',         bg = 'DeepSkyBlue3' })
hi('PmenuThumb',                { bg = 'Red' })
hi('Constant',                  { fg = 'Red2',          bold = false })
hi('Type',                     { fg = 'CornflowerBlue', bold = false })
hi('Boolean',                   { link = 'Constant' })
hi('Character',                 { link = 'Constant' })
hi('Comment',                   { fg = 'Blue3' })
hi('DiagnosticError',           { fg = 'Red' })
hi('DiagnosticHint',            { fg = 'Black' })
hi('DiagnosticInfo',            { fg = 'LightBlue' })
hi('DiagnosticOk',              { fg = 'LightGreen' })
hi('DiagnosticUnderlineError',  { sp = 'Red',          underline = true })
hi('DiagnosticUnderlineHint',   { sp = 'LightGrey',     underline = true })
hi('DiagnosticUnderlineInfo',   { sp = 'LightBlue',     underline = true })
hi('DiagnosticUnderlineOk',     { sp = 'LightGreen',    underline = true })
hi('DiagnosticUnderlineWarn',   { sp = 'Orange',        underline = true })
hi('DiagnosticWarn',             { fg = 'Orange' })
hi('Float',                     { link = 'Number' })
hi('Function',                  { link = 'Identifier' })
hi('Number',                    { fg = 'Green3' })
hi('Statement',                { fg = 'DarkOrange3',    bold = false })
hi('String',                   { fg = 'Brown',          bold = false })
hi('CursorColumn',             { bg = 'Grey90' })
hi('CursorLine',               { bg = '#ffffff' })
hi('CursorLineNr',             { fg = 'Brown',          bold = true })
hi('DiffAdd',                  { bg = 'LightBlue' })
hi('DiffChange',               { bg = 'LightMagenta' })
hi('DiffDelete',               { fg = 'Blue',           bg = 'LightCyan', bold = true })
hi('Directory',                { fg = 'Blue' })
hi('FoldColumn',               { fg = 'DarkBlue',       bg = 'Grey' })
hi('Folded',                   { fg = 'DarkBlue',       bg = 'LightGrey' })
hi('Identifier',               { fg = 'Black' })
hi('Ignore',                   { fg = 'White' })
hi('LineNr',                   { fg = 'CornflowerBlue', bold = false })
hi('MatchParen',               { bg = 'Cyan' })
hi('MoreMsg',                  { fg = 'SeaGreen',       bold = true })
hi('PreProc',                  { fg = 'RoyalBlue4',     bold = false })
hi('Question',                 { fg = 'SeaGreen',       bold = true })
hi('Search',                   { bg = 'Yellow' })
hi('SignColumn',               { fg = 'Blue' })
hi('Special',                  { fg = 'Red2' })
hi('SpecialKey',               { fg = 'Red' })
hi('SpellBad',                 { sp = 'Red',            undercurl = true })
hi('SpellCap',                 { sp = 'Blue',           undercurl = true })
hi('SpellLocal',               { sp = 'DarkCyan',       undercurl = true })
hi('SpellRare',                { sp = 'Magenta',        undercurl = true })
hi('StatusLineTerm',           { fg = 'White',          bg = 'DarkGreen', bold = true })
hi('StatusLineTermNC',         { fg = 'White',          bg = 'DarkGreen' })
hi('TabLine',                  { bg = 'LightGrey',      underline = true })
hi('Title',                    { fg = 'Magenta',        bold = true })
hi('Underlined',               { fg = 'SlateBlue',      underline = true })
hi('WarningMsg',               { fg = 'Red' })
hi('Added',                    { fg = 'Green' })
hi('ColorColumn',              { bg = 'LightRed' })
hi('Removed',                  { fg = 'Red' })
hi('RenderMarkdownH1Bg',       { bg = 'LightGreen' })
hi('diffFile',                 { fg = 'Purple' })
hi('diffNewFile',              { fg = 'Blue' })
hi('diffOldFile',              { fg = 'Red' })
hi('Whitespace',               { fg = '#aaaa99' })
hi('Visual',                   { bg = '#cac9c9' })
hi('@property',                { fg = '#000000' })
hi('@_parent',                 { fg = '#000000' })
hi('@string',                  { link = 'String' })
hi('@keyword.directive',       { fg = 'RoyalBlue4',     bold = false })
hi('@keyword.import',          { fg = 'RoyalBlue4',     bold = false })
hi('@type.builtin',            { link = 'Type' })
hi('@variable',                { link = 'Normal' })
hi('Delimeter',                { link = 'Normal' })
--stylua: ignore end
